export {
	deserialize,
	deserializeTimeline,
	type Project,
	parseTimeline,
} from "./deserialize.ts";
export { migrate, UnknownSchemaVersionError } from "./migrations.ts";
export {
	type AudioClipJSON,
	type AudioTrackJSON,
	type BoxJSON,
	type CaptionClipJSON,
	type CaptionTrackJSON,
	type CircleJSON,
	CURRENT_SCHEMA_VERSION,
	type GroupJSON,
	type ImageJSON,
	type Layer2DJSON,
	type Layer3DJSON,
	type LayerJSON,
	type LineJSON,
	type NodeJSON,
	type NumberClipJSON,
	type NumberKeyframeJSON,
	type NumberTrackJSON,
	type ProjectJSON,
	type RectJSON,
	type SceneJSON,
	type SceneMetaJSON,
	type TextJSON,
	type TimelineJSON,
	type TrackJSON,
	type TrackTargetByIdJSON,
	type TrackTargetByPathJSON,
	type TrackTargetJSON,
	type Transform2DJSON,
	type Transform3DJSON,
	type TransformJSON,
} from "./schema.ts";
export { serialize, serializeScene, serializeTimeline } from "./serialize.ts";
