export {
	applyNodeOps,
	applyOverlay,
	CURRENT_OVERLAY_VERSION,
	deserializeOverlay,
	emptyOverlay,
	migrateOverlay,
	type NodeAddition,
	type NodeDeletion,
	type NodeKind,
	type Overlay,
	type OverlayJSON,
	type OverrideValue,
	type PropertyOverride,
	parseOverlay,
} from "./overlay/index.ts";
export {
	type BoxJSON,
	CURRENT_SCHEMA_VERSION,
	deserialize,
	deserializeTimeline,
	type GroupJSON,
	type Layer2DJSON,
	type Layer3DJSON,
	type LayerJSON,
	migrate,
	type NodeJSON,
	type NumberClipJSON,
	type NumberKeyframeJSON,
	type NumberTrackJSON,
	type Project,
	type ProjectJSON,
	parseTimeline,
	type RectJSON,
	type SceneJSON,
	type SceneMetaJSON,
	serialize,
	serializeScene,
	serializeTimeline,
	type TimelineJSON,
	type TrackJSON,
	type TrackTargetByIdJSON,
	type TrackTargetByPathJSON,
	type TrackTargetJSON,
	type Transform2DJSON,
	type Transform3DJSON,
	type TransformJSON,
	UnknownSchemaVersionError,
} from "./project/index.ts";
export { type Property, prop } from "./reactive/index.ts";
export {
	type Compositor,
	type CreateCompositorOptions,
	type CreateLayerRenderer,
	type CreateLayerRendererOptions,
	createCompositor,
	createPixiLayerRenderer,
	createThreeLayerRenderer,
	type LayerRenderer,
} from "./render/index.ts";
export {
	assertSceneStructure,
	assertUniqueChildNames,
	assertUniqueLayerNames,
	type Box,
	type CreateBoxOptions,
	type CreateGroupOptions,
	type CreateLayer2DOptions,
	type CreateLayer3DOptions,
	type CreateRectOptions,
	type CreateSceneOptions,
	createBox,
	createGroup,
	createLayer2D,
	createLayer3D,
	createRect,
	createScene,
	createTransform2D,
	createTransform3D,
	findNodeById,
	findNodeByPath,
	type Group,
	type Layer,
	type Node,
	NodeType,
	type Rect,
	type Scene,
	type Scene2DLayer,
	type Scene3DLayer,
	type SceneMeta,
	type Transform,
	type Transform2D,
	type Transform2DInit,
	type Transform3D,
	type Transform3DInit,
	TransformKind,
	type Vec3,
} from "./scene/index.ts";
export {
	applyTimeline,
	type Clip,
	type CreateClipOptions,
	type CreateKeyframeOptions,
	type CreateTimelineOptions,
	type CreateTrackOptions,
	createClip,
	createKeyframe,
	createPlaybackController,
	createTimeline,
	createTrack,
	type EasingFn,
	EasingName,
	easings,
	evaluateClip,
	evaluateTrack,
	isTrackTargetByPath,
	type Keyframe,
	type NumberTrack,
	type PlaybackController,
	type PlaybackControllerOptions,
	type PlaybackScheduler,
	type PlaybackState,
	type Timeline,
	type Track,
	TrackKind,
	type TrackTarget,
	type TrackTargetById,
	type TrackTargetByPath,
} from "./timeline/index.ts";
export { VERSION } from "./version.ts";
