/// <reference path="./render/troika-three-text.d.ts" />

export {
	type AudioBufferLike,
	type AudioPlayer,
	type AudioPlayerOptions,
	computePeaks,
	createAudioPlayer,
	decodeAudio,
	type Peaks,
} from "./audio/index.ts";
export { parseSRT, parseVTT, serializeSRT, serializeVTT } from "./captions/index.ts";
export {
	type ExportProgress,
	type ExportVideoOptions,
	exportVideo,
	mixTimelineAudio,
} from "./export/index.ts";
export {
	applyNodeOps,
	applyOverlay,
	applyOverlayMeta,
	CURRENT_OVERLAY_VERSION,
	deserializeOverlay,
	emptyOverlay,
	type MetaOverride,
	migrateOverlay,
	type NodeAddition,
	type NodeDeletion,
	type NodeKind,
	type Overlay,
	type OverlayJSON,
	type OverrideValue,
	type PropertyOverride,
	parseOverlay,
} from "./overlay/index.ts";
export {
	type AudioClipJSON,
	type AudioTrackJSON,
	type BoxJSON,
	type CaptionClipJSON,
	type CaptionTrackJSON,
	type CircleJSON,
	CURRENT_SCHEMA_VERSION,
	deserialize,
	deserializeTimeline,
	type GroupJSON,
	type ImageJSON,
	type Layer2DJSON,
	type Layer3DJSON,
	type LayerJSON,
	type LineJSON,
	migrate,
	type NodeJSON,
	type NumberClipJSON,
	type NumberKeyframeJSON,
	type NumberTrackJSON,
	type Project,
	type ProjectJSON,
	parseTimeline,
	type RectJSON,
	type SceneJSON,
	type SceneMetaJSON,
	serialize,
	serializeScene,
	serializeTimeline,
	type TextJSON,
	type TimelineJSON,
	type TrackJSON,
	type TrackTargetByIdJSON,
	type TrackTargetByPathJSON,
	type TrackTargetJSON,
	type Transform2DJSON,
	type Transform3DJSON,
	type TransformJSON,
	UnknownSchemaVersionError,
} from "./project/index.ts";
export { type Property, prop } from "./reactive/index.ts";
export {
	type Compositor,
	type CreateCompositorOptions,
	type CreateLayerRenderer,
	type CreateLayerRendererOptions,
	createCompositor,
	createPixiLayerRenderer,
	createThreeLayerRenderer,
	type LayerRenderer,
} from "./render/index.ts";
export {
	assertSceneStructure,
	assertUniqueChildNames,
	assertUniqueLayerNames,
	type Box,
	type Circle,
	type CreateBoxOptions,
	type CreateCircleOptions,
	type CreateGroupOptions,
	type CreateImageOptions,
	type CreateLayer2DOptions,
	type CreateLayer3DOptions,
	type CreateLineOptions,
	type CreateRectOptions,
	type CreateSceneOptions,
	type CreateTextOptions,
	createBox,
	createCircle,
	createGroup,
	createImage,
	createLayer2D,
	createLayer3D,
	createLine,
	createRect,
	createScene,
	createText,
	createTransform2D,
	createTransform3D,
	findNodeById,
	findNodeByPath,
	type Group,
	type Image,
	type Layer,
	type Line,
	type Node,
	NodeType,
	type Rect,
	type Scene,
	type Scene2DLayer,
	type Scene3DLayer,
	type SceneMeta,
	type Text,
	TextAlign,
	type Transform,
	type Transform2D,
	type Transform2DInit,
	type Transform3D,
	type Transform3DInit,
	TransformKind,
	type Vec3,
} from "./scene/index.ts";
export {
	type AudioClip,
	type AudioTrack,
	applyTimeline,
	type CaptionClip,
	type CaptionTrack,
	type Clip,
	type CreateAudioClipOptions,
	type CreateAudioTrackOptions,
	type CreateCaptionClipOptions,
	type CreateCaptionTrackOptions,
	type CreateClipOptions,
	type CreateKeyframeOptions,
	type CreateTimelineOptions,
	type CreateTrackOptions,
	createAudioClip,
	createAudioTrack,
	createCaptionClip,
	createCaptionTrack,
	createClip,
	createKeyframe,
	createPlaybackController,
	createTimeline,
	createTrack,
	type EasingFn,
	EasingName,
	easings,
	evaluateCaptionTrack,
	evaluateClip,
	evaluateTrack,
	isAudioTrack,
	isCaptionTrack,
	isNumberTrack,
	isTrackTargetByPath,
	type Keyframe,
	type NumberTrack,
	type PlaybackController,
	type PlaybackControllerOptions,
	type PlaybackScheduler,
	type PlaybackState,
	type Timeline,
	type Track,
	TrackKind,
	type TrackTarget,
	type TrackTargetById,
	type TrackTargetByPath,
} from "./timeline/index.ts";
export {
	createKokoroProvider,
	floatPcmToWav,
	type KokoroOptions,
	type TtsPreviewOptions,
	type TtsProvider,
	type TtsRequest,
	type TtsResult,
	type TtsVoice,
	type TtsWarmUpProgress,
} from "./tts/index.ts";
export { VERSION } from "./version.ts";
