export {
	CURRENT_SCHEMA_VERSION,
	deserialize,
	type GroupJSON,
	type Layer2DJSON,
	type Layer3DJSON,
	type LayerJSON,
	migrate,
	type ProjectJSON,
	type SceneJSON,
	type SceneMetaJSON,
	serialize,
	type Transform2DJSON,
	type Transform3DJSON,
	type TransformJSON,
	UnknownSchemaVersionError,
} from "./project/index.ts";
export { type Property, prop } from "./reactive/index.ts";
export {
	type CreateGroupOptions,
	type CreateLayer2DOptions,
	type CreateLayer3DOptions,
	type CreateSceneOptions,
	createGroup,
	createLayer2D,
	createLayer3D,
	createScene,
	createTransform2D,
	createTransform3D,
	type Group,
	type Layer,
	type Node,
	NodeType,
	type Scene,
	type Scene2DLayer,
	type Scene3DLayer,
	type SceneMeta,
	type Transform,
	type Transform2D,
	type Transform2DInit,
	type Transform3D,
	type Transform3DInit,
	TransformKind,
	type Vec3,
} from "./scene/index.ts";
export { VERSION } from "./version.ts";
